l_english:
 SETTING_HINTS:0 "Podpowiedzi"
 SETTING_LAST_HOST:0 "Ostatni gospodarz"
 SETTING_LAST_PLAYER:0 "Ostatni gracz"
 SETTING_DIFFICULTY:0 "Poziom trudności"
 SETTING_AUTOSAVE:0 "Interwał autozapisów"
 SETTING_DEBUG_SAVES:0 "Ilość zapisów debug"
 SETTING_WINDOW_MOVE_TIME:0 "Czas przesunięcia okna"
 SETTING_RADIAL_STAY_TIME:0 "Czas pobytu promieniowego"
 SETTING_CAMERA_FACE_NORTH:0 "Kamera skierowana na północ"
 SETTING_AUTOSAVE_TO_CLOUD:0 "Autozapis do chmury"
 SETTING_DISABLED_ALERTS:0 "Wyłączone alerty"
 SETTING_DISABLED_HINTS:0 "Wyłączone podpowiedzi"
 SETTING_FOCUS_ON_COMBAT:0 "Skupienie na bitwie"
 SETTING_FOCUS_ON_COMBAT_TOOLTIP:0 "Określa, czy prędkość gry ma być ograniczona podczas obserwowania bitwy."
 SETTING_PROVINCE_NAMES:0 "Nazwy prowincji"
 SETTING_MAX_TICKS_AHEAD:0 "Max ticks ahead"
 MAPNAME_MODE_ALWAYS_ON:0 "Zawsze włączone"
 MAPNAME_MODE_ALWAYS_OFF:0 "Zawsze wyłączone"
 MAPNAME_MODE_MOUSE_OVER:0 "Najedź myszką"
 MAPNAME_MODE_DEFAULT:0 "Domyślny"
 SETTING_FILL_IN_IMPASSABLE_TERRAIN:0 "Wypełnij nieprzekraczalny teren"
 SETTING_PAUSE_ON_EVENTS:0 "Zapazuj na wydarzeniach"
 SETTING_ADVICE:0 "Porada dotycząca alertu"
 SETTING_ADVICE_TOOLTIP:0 "Określa, czy po kliknięciu ikony alertu będą wyświetlane porady i podkreślenia"
  # Map
 SETTING_DRAW_TERRAIN:0 "Rysuj teren"
 SETTING_DRAW_WATER:0 "Rysuj wodę"
 SETTING_DRAW_BORDERS:0 "Rysuj granice"
 SETTING_DRAW_TREES:0 "Rysuj drzewa"
 SETTING_DRAW_RIVERS:0 "Rysuj rzeki"
 SETTING_DRAW_POSTFX:0 "Rysuj postfx"
 SETTING_DRAW_SKY:0 "Rysuj niebo"
 SETTING_DRAW_BLOOM:0 "Rysuj bloom"
 SETTING_DRAW_TOOLTIPS:0 "Rysuj okienka"
 SETTING_DRAW_CITYSPRAWL:0 "Rysuj rozrost miast"
 SETTING_DRAW_SHADOWS:0 "Rysuj cienie"
  # Outliner
 SETTING_OUTLINER_SHOW_OUTLINER:0 "Pokaż przybornik"
 SETTING_OUTLINER_PLAYER_ARMIES:0 "Pokaż armie gracza"
 SETTING_OUTLINER_PLAYER_NAVIES:0 "Pokaż floty gracza"
 SETTING_OUTLINER_AUTOMATED_NAVIES:0 "Pokaż floty gracza"
 SETTING_OUTLINER_AUTOMATED_ARMIES:0 "Pokaż armie gracza"
 SETTING_OUTLINER_PROVINCIAL_ARMIES:0 "Pokaż armie gracza"
 SETTING_OUTLINER_COMBATS:0 "Pokaż bitwy"
 SETTING_OUTLINER_SIEGES_OUR:0 "Pokaż nasze oblężenia"
 SETTING_OUTLINER_SIEGES_HOSTILE:0 "Pokaż wrogie oblężenia"
 SETTING_OUTLINER_DISLOYAL_CHARACTERS:0 "Pokaż nielojalne postacie"
 SETTING_OUTLINER_CONSTRUCTIONS_BUILDINGS:0 "Pokaż konstrukcję budowli"
 SETTING_OUTLINER_CONSTRUCTIONS_MILITARY:0 "Pokaż konstrukcję militarną"
 SETTING_OUTLINER_PROVINCEMODIFIER:0 "Pokaż ulepszenia terytoriów"
 SETTING_OUTLINER_ACTIVE_WARS:0 "Pokaż aktualne wojny"
 SETTING_OUTLINER_ACTIVE_DIPLOMACY:0 "Pokaż aktywną dyplomację"
 SETTING_OUTLINER_HUMAN_PLAYERS:0 "Pokaż ludzkich graczy"
